ALTER SESSION SET CONTAINER = XEPDB1;

DECLARE
  user_exists INTEGER;
BEGIN
  SELECT COUNT(*) INTO user_exists
  FROM dba_users
  WHERE username = UPPER('hr_xml_lab');

  IF user_exists = 0 THEN
    EXECUTE IMMEDIATE 'ALTER SESSION SET "_ORACLE_SCRIPT"=true';
    EXECUTE IMMEDIATE 'CREATE USER hr_xml_lab IDENTIFIED BY hr_xml_lab_pwd DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
  END IF;
END;
/

GRANT CONNECT, RESOURCE, XDBADMIN, CREATE VIEW, CREATE SYNONYM TO hr_xml_lab;
GRANT EXECUTE ON DBMS_XMLSCHEMA TO hr_xml_lab;
GRANT EXECUTE ON DBMS_XMLDOM TO hr_xml_lab;
GRANT EXECUTE ON DBMS_XDB TO hr_xml_lab;

GRANT SELECT ON HR.EMPLOYEES TO hr_xml_lab;
GRANT SELECT ON HR.DEPARTMENTS TO hr_xml_lab;
GRANT SELECT ON HR.LOCATIONS TO hr_xml_lab;

