ALTER SESSION SET CONTAINER = XEPDB1;

BEGIN
  EXECUTE IMMEDIATE 'CREATE OR REPLACE DIRECTORY LAB_DOCS AS ''/opt/oracle/lab/docs/xml''';
  EXECUTE IMMEDIATE 'GRANT READ, WRITE ON DIRECTORY LAB_DOCS TO hr_xml_lab';
  EXECUTE IMMEDIATE 'GRANT READ, WRITE ON DIRECTORY LAB_DOCS TO hr';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-1031) THEN
      RAISE;
    END IF;
END;
/

