-- Ejecutar como usuario hr_xml_lab
SET SERVEROUTPUT ON

DECLARE
  l_schema_url CONSTANT VARCHAR2(128) := 'http://example.com/hr/employees';
  l_schema_doc CLOB := q'~<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://example.com/hr/employees"
           xmlns="http://example.com/hr/employees"
           elementFormDefault="qualified">
  <xs:element name="employees">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="employee" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="employeeId" type="xs:integer"/>
              <xs:element name="firstName" type="xs:string" minOccurs="0"/>
              <xs:element name="lastName" type="xs:string"/>
              <xs:element name="email" type="xs:string"/>
              <xs:element name="phoneNumber" type="xs:string" minOccurs="0"/>
              <xs:element name="hireDate" type="xs:date"/>
              <xs:element name="jobId" type="xs:string"/>
              <xs:element name="salary" type="xs:decimal"/>
              <xs:element name="department">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="departmentId" type="xs:integer"/>
                    <xs:element name="departmentName" type="xs:string"/>
                    <xs:element name="location">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="city" type="xs:string"/>
                          <xs:element name="countryId" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>~';
BEGIN
  BEGIN
    DBMS_XMLSCHEMA.deleteSchema(
      schemaURL     => l_schema_url,
      delete_option => DBMS_XMLSCHEMA.DELETE_CASCADE_FORCE
    );
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -31000 THEN
        RAISE;
      END IF;
  END;

  DBMS_XMLSCHEMA.registerSchema(
    schemaURL     => l_schema_url,
    schemaDoc     => XMLType.createXML(l_schema_doc),
    local         => TRUE,
    genTypes      => FALSE,
    genTables     => FALSE,
    options       => DBMS_XMLSCHEMA.REGISTER_BINARYXML
  );

  DBMS_OUTPUT.put_line('Esquema XML registrado correctamente.');
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE employee_department_xml PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

CREATE TABLE employee_department_xml (
  id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  payload XMLTYPE
) XMLTYPE COLUMN payload STORE AS BINARY XML
  XMLSCHEMA "http://example.com/hr/employees"
  ELEMENT   "employees";

COMMENT ON TABLE employee_department_xml IS 'Datos de empleados y departamentos validados por el esquema XML http://example.com/hr/employees';

